### ISSUE TITLE
[enhancement request] Timestamp Style Option

### ISSUE THREAD

**Issue by Turtlepaw** [Dot32IsCool/discord-timestamp-generator#4]
The option to change the [timestamp style](https://discord.com/developers/docs/reference#message-formatting-timestamp-styles).

**Comment by Dot32Dev** [comment]
Should i turn the "relative" in the h1 into a dropdown menu to select type? It's a feature i've been considering for a while

**Comment by Turtlepaw** [comment]
👍 That sounds good!

**Comment by Dot32Dev** [comment]
sorry for late reply,, i'm still not sure i want this, the website does brand itself as *relative* discord timestamp generator after all. I definitely will think about it more though.
