### ISSUE TITLE
if you select "date", it shows you a date actually month ago

### ISSUE THREAD

**Issue by roflsunriz** [Dot32IsCool/discord-timestamp-generator#5]
current local time:
19:40:10 JST (UTC+9)
Tuesday, 12 April 2022
https://www.timeanddate.com/worldclock/japan/tokyo
but this tool shows:
![Screenshot_20220412-194213](https://user-images.githubusercontent.com/8847851/162943031-b6c23169-2094-4c0a-b5b3-7aec0048486a.jpg)

but copied rusult is accurate.

**Comment by Dot32Dev** [comment]
Oh wow! This is incredibly strange, and i'm getting the same bug, i'll have to investigate this
